{% set python_min = "3.10" %}
package:
  name: ro-yolov7
  version: "0.1.0"

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - opencv
    - pillow
    - pyyaml
    - requests
    - scipy
    - pytorch
    - torchvision
    - tqdm

test:
  requires:
    - pip
    - python {{ python_min }}.*
  commands:
    - pip check
  imports:
    - ro_yolov7

about:
  home: https://github.com/WongKinYiu/yolov7
  license: GPL-3.0-only
  license_file: LICENSE.md
  summary: YOLOv7 -- Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors
